<?php

// autoload_static.php @generated by Composer

namespace HM\Two_Factor_Passkey\Vendor\Composer\Autoload;

class ComposerStaticInitf8a05fdf0cf6edaebc56b52b28c52dfa
{
    public static $prefixLengthsPsr4 = array (
        'H' =>
        array (
            'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\' => 45,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\' =>
        array (
            0 => __DIR__ . '/..' . '/lbuchs/webauthn/src',
        ),
    );

    public static $classMap = array (
        'HM\\Two_Factor_Passkey\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\AttestationObject' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/AttestationObject.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\AuthenticatorData' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/AuthenticatorData.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\AndroidKey' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/AndroidKey.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\AndroidSafetyNet' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/AndroidSafetyNet.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\Apple' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/Apple.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\FormatBase' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/FormatBase.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\None' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/None.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\Packed' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/Packed.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\Tpm' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/Tpm.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\U2f' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Attestation/Format/U2f.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Binary\\ByteBuffer' => __DIR__ . '/..' . '/lbuchs/webauthn/src/Binary/ByteBuffer.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\CBOR\\CborDecoder' => __DIR__ . '/..' . '/lbuchs/webauthn/src/CBOR/CborDecoder.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\WebAuthn' => __DIR__ . '/..' . '/lbuchs/webauthn/src/WebAuthn.php',
        'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\WebAuthnException' => __DIR__ . '/..' . '/lbuchs/webauthn/src/WebAuthnException.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf8a05fdf0cf6edaebc56b52b28c52dfa::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf8a05fdf0cf6edaebc56b52b28c52dfa::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf8a05fdf0cf6edaebc56b52b28c52dfa::$classMap;

        }, null, ClassLoader::class);
    }
}
