<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitf8a05fdf0cf6edaebc56b52b28c52dfa
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('HM\Two_Factor_Passkey\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \HM\Two_Factor_Passkey\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitf8a05fdf0cf6edaebc56b52b28c52dfa', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \HM\Two_Factor_Passkey\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitf8a05fdf0cf6edaebc56b52b28c52dfa', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\HM\Two_Factor_Passkey\Vendor\Composer\Autoload\ComposerStaticInitf8a05fdf0cf6edaebc56b52b28c52dfa::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
