<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'HM\\Two_Factor_Passkey\\Vendor\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\AttestationObject' => $vendorDir . '/lbuchs/webauthn/src/Attestation/AttestationObject.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\AuthenticatorData' => $vendorDir . '/lbuchs/webauthn/src/Attestation/AuthenticatorData.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\AndroidKey' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/AndroidKey.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\AndroidSafetyNet' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/AndroidSafetyNet.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\Apple' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/Apple.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\FormatBase' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/FormatBase.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\None' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/None.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\Packed' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/Packed.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\Tpm' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/Tpm.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Attestation\\Format\\U2f' => $vendorDir . '/lbuchs/webauthn/src/Attestation/Format/U2f.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\Binary\\ByteBuffer' => $vendorDir . '/lbuchs/webauthn/src/Binary/ByteBuffer.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\CBOR\\CborDecoder' => $vendorDir . '/lbuchs/webauthn/src/CBOR/CborDecoder.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\WebAuthn' => $vendorDir . '/lbuchs/webauthn/src/WebAuthn.php',
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\WebAuthnException' => $vendorDir . '/lbuchs/webauthn/src/WebAuthnException.php',
);
