<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'HM\\Two_Factor_Passkey\\Vendor\\lbuchs\\WebAuthn\\' => array($vendorDir . '/lbuchs/webauthn/src'),
);
